# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'docdialog.ui'
#
# Created: Mon May 25 14:07:18 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(467, 346)
        Dialog.setSizeGripEnabled(False)
        self.verticalLayout_6 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtGui.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtGui.QLabel(self.tabGeneral)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtGui.QLabel(self.tabGeneral)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.tabGeneral)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.tabGeneral)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.name = QtGui.QLineEdit(self.tabGeneral)
        self.name.setObjectName("name")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.name)
        self.author = QtGui.QLineEdit(self.tabGeneral)
        self.author.setObjectName("author")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.author)
        self.year = QtGui.QSpinBox(self.tabGeneral)
        self.year.setMaximum(2147483647)
        self.year.setObjectName("year")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.year)
        self.label_6 = QtGui.QLabel(self.tabGeneral)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.theme = QtGui.QComboBox(self.tabGeneral)
        self.theme.setObjectName("theme")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.theme)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.docFileName = QtGui.QLineEdit(self.tabGeneral)
        self.docFileName.setObjectName("docFileName")
        self.horizontalLayout.addWidget(self.docFileName)
        self.selectDocFileName = QtGui.QPushButton(self.tabGeneral)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectDocFileName.sizePolicy().hasHeightForWidth())
        self.selectDocFileName.setSizePolicy(sizePolicy)
        self.selectDocFileName.setMinimumSize(QtCore.QSize(20, 20))
        self.selectDocFileName.setMaximumSize(QtCore.QSize(20, 20))
        self.selectDocFileName.setObjectName("selectDocFileName")
        self.horizontalLayout.addWidget(self.selectDocFileName)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtGui.QScrollArea(self.tab_2)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 425, 324))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.annotation = QtGui.QTextEdit(self.groupBox)
        self.annotation.setObjectName("annotation")
        self.verticalLayout.addWidget(self.annotation)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableOfContents = QtGui.QTextEdit(self.groupBox_2)
        self.tableOfContents.setObjectName("tableOfContents")
        self.verticalLayout_2.addWidget(self.tableOfContents)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.references = QtGui.QTextEdit(self.groupBox_3)
        self.references.setObjectName("references")
        self.verticalLayout_3.addWidget(self.references)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_6.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Редактирование документа", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Тема работы:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Название работы:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Автор:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Год издания:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Файл работы:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDocFileName.setToolTip(QtGui.QApplication.translate("Dialog", "Выбор файла работы", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDocFileName.setStatusTip(QtGui.QApplication.translate("Dialog", "Выбор файла работы", None, QtGui.QApplication.UnicodeUTF8))
        self.selectDocFileName.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), QtGui.QApplication.translate("Dialog", "Основное", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Аннотация", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Оглавление", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Список литературы", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Дополнительное", None, QtGui.QApplication.UnicodeUTF8))

